version: '3.8'

services:
  frontend:
    build: 
      context: ./way-esports/frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - VITE_API_URL=http://localhost:3002
      - VITE_BOT_USERNAME=way_esports_bot
      - VITE_TON_NETWORK=mainnet
    depends_on:
      - backend
    networks:
      - way-esports-network

  backend:
    build: 
      context: ./way-esports-backend
      dockerfile: Dockerfile
    ports:
      - "3002:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb+srv://vb917185:hJoJm47FxYT8kSAP@cluster1.ey2ubm6.mongodb.net/way-esports
      - JWT_SECRET=dev-secret-key-for-local-development-only
      - CORS_ORIGIN=http://localhost:3001
    networks:
      - way-esports-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  bot:
    build: 
      context: ./way-esports-bot
      dockerfile: Dockerfile
    ports:
      - "3003:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - BOT_TOKEN=7623512865:AAFP3g0hQbd-zUVaSw8qoqrvoVPiHzL2kMk
      - MONGODB_URI=mongodb+srv://vb917185:hJoJm47FxYT8kSAP@cluster1.ey2ubm6.mongodb.net/way-esports
      - BACKEND_URL=http://backend:3001
      - FRONTEND_URL=http://frontend:3001
      - TON_NETWORK=mainnet
    depends_on:
      - backend
    networks:
      - way-esports-network

networks:
  way-esports-network:
    driver: bridge

volumes:
  mongodb_data: