version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: way-esports-app
    env_file:
      - ./way-esports-backend/.env
    ports:
      - "3000:3000"
      - "80:80"
    restart: unless-stopped
