version: '3.8'

services:
  tine-frontend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-build
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./way-esports/frontend:/app/way-esports/frontend
      - /app/way-esports/frontend/node_modules
    command: ["npm", "run", "dev"]

  tine-backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-build
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://vb917185:hJoJm47FxYT8kSAP@cluster1.ey2ubm6.mongodb.net/
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./way-esports-backend:/app/way-esports-backend
      - /app/way-esports-backend/node_modules
    depends_on:
      - mongo
      - redis
    command: ["npm", "run", "dev"]

  mongo:
    restart: unless-stopped
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  redis:
    restart: unless-stopped
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
