services:
  backend:
    build:
      context: ./way-esports-backend
      dockerfile: Dockerfile
    container_name: way-backend
    env_file:
      - ./way-esports-backend/.env
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./way-esports-frontend
      dockerfile: Dockerfile
    container_name: way-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
