name: Deploy TimeWeb

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '18'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: way-esports/frontend/package-lock.json

      - name: Install dependencies
        working-directory: way-esports/frontend
        run: npm ci

      - name: Build frontend
        working-directory: way-esports/frontend
        run: |
          npm run build
          npm run build:zip

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: way-esports/frontend/dist/
          retention-days: 7

  build-backend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: way-esports-backend/package-lock.json

      - name: Install dependencies
        working-directory: way-esports-backend
        run: npm ci

      - name: Build backend
        working-directory: way-esports-backend
        run: npm run build

      - name: Upload backend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: |
            way-esports-backend/dist/
            way-esports-backend/package.json
            way-esports-backend/package-lock.json
          retention-days: 7

  docker-build:
    needs: [build-frontend, build-backend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-on-server:
    needs: docker-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Test SSH connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          debug: true
          script: |
            echo "SSH connection successful!"
            whoami
            pwd
            echo "Testing basic commands..."

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          debug: true
          script: |
            set -e
            cd ${{ secrets.REPO_PATH }}
            git pull --rebase --autostash || true
            docker compose pull || true
            docker compose up -d --build
            docker system prune -f

      - name: Verify deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          debug: true
          script: |
            cd ${{ secrets.REPO_PATH }}
            echo "Latest commit on server:"
            git rev-parse --short HEAD
            git log -1 --pretty=format:"%h %ad %s" --date=iso
            echo "--- Docker containers status ---"
            docker compose ps
            echo "--- Frontend dist presence ---"
            test -d way-esports/frontend/dist && ls -lah way-esports/frontend/dist | head -n 5 || echo "Frontend dist not found"
