name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          timeout: 60s
          command_timeout: 15m
          script: |
            set -e
            echo "🚀 Starting deployment..."
            cd ${{ secrets.REPO_PATH }}

            echo "📥 Pulling latest code..."
            git pull origin main --rebase --autostash

            echo "🐳 Building and starting containers..."
            docker compose down
            docker compose up -d --build --remove-orphans

            echo "🧹 Cleaning up..."
            docker system prune -f

            echo "✅ Deployment completed!"
            echo "📊 Status:"
            docker compose ps
