name: Build & Deploy (prod)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: ghcr.io/virall228/way-esports-backend:latest
  IMAGE_FRONTEND: ghcr.io/virall228/way-esports-frontend:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # BACKEND
      - name: Build & Push backend
        uses: docker/build-push-action@v6
        with:
          context: ./way-esports-backend
          file: ./way-esports-backend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_BACKEND }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # FRONTEND
      - name: Build & Push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./way-esports-frontend
          file: ./way-esports-frontend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_FRONTEND }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -euo pipefail
            sudo mkdir -p /opt/way-esports/secrets
            sudo mkdir -p /opt/way-esports
            cd /opt/way-esports

            # Клонируем или обновляем репозиторий (нижний регистр)
            if [ ! -d "way-esports/.git" ]; then
              git clone https://github.com/virall228/way-esports.git
            fi
            cd way-esports
            git fetch --all --prune
            git checkout main
            git pull --rebase

            # Проверяем, что env существует
            if [ ! -f /opt/way-esports/secrets/backend.env ]; then
              echo "ERROR: /opt/way-esports/secrets/backend.env not found" >&2
              exit 1
            fi

            # Поднимаем сервисы
            COMPOSE_FILE=docker-compose.prod.yml
            if [ ! -f "$COMPOSE_FILE" ]; then
              COMPOSE_FILE=docker-compose.yml
            fi

            docker login ghcr.io -u ${{ secrets.GHCR_USER || github.actor }} -p ${{ secrets.GHCR_TOKEN || secrets.GITHUB_TOKEN }}
            docker compose -f "$COMPOSE_FILE" pull || true
            docker compose -f "$COMPOSE_FILE" up -d --build
            docker compose -f "$COMPOSE_FILE" ps
