name: Build & Auto-Deploy (Watchtower)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: ghcr.io/virall228/way-esports-backend:latest
  IMAGE_FRONTEND: ghcr.io/virall228/way-esports-frontend:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # BACKEND
      - name: Build & Push backend
        uses: docker/build-push-action@v6
        with:
          context: ./way-esports-backend
          file: ./way-esports-backend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_BACKEND }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # FRONTEND
      - name: Build & Push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./way-esports-frontend
          file: ./way-esports-frontend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_FRONTEND }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Notify deployment
        run: |
          echo "✅ Images built and pushed successfully!"
          echo "🚀 Watchtower will automatically update containers within 60 seconds"
          echo ""
          echo "📊 Build Summary:"
          echo "  Backend: ${{ env.IMAGE_BACKEND }}"
          echo "  Frontend: ${{ env.IMAGE_FRONTEND }}"
          echo ""
          echo "⏰ Next update: Watchtower checks every 60 seconds"
